# Generated by Django 3.1.6 on 2021-02-12 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Databasess',
            new_name='sample',
        ),
    ]
