# Generated by Django 3.1.6 on 2021-02-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_auto_20210213_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.CharField(max_length=25)),
                ('message', models.CharField(max_length=25)),
            ],
        ),
    ]
