# Generated by Django 3.1.6 on 2021-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0003_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
