# Generated by Django 3.1.6 on 2021-02-21 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0005_auto_20210222_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='name',
        ),
        migrations.DeleteModel(
            name='post',
        ),
    ]
