# Generated by Django 3.1.6 on 2021-02-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_auto_20210222_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('post_number', models.IntegerField()),
                ('message', models.CharField(max_length=25)),
            ],
        ),
    ]
